# File: laravel-mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-mysql-deployment
  labels:
    app: laravel-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-mysql
  template:
    metadata:
      labels:
        app: laravel-mysql
    spec:
      containers:
        # Laravel Web Container
        - name: web
      image: sovichet12/laravel-web:latest
      imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "mysql"  # Matches MySQL service name
            - name: DB_DATABASE
              value: "laravel_final"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql_root_password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"

        # MySQL Database Container
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql_root_password
            - name: MYSQL_DATABASE
              value: "laravel_final"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
      volumes:
        - name: mysql-data
          emptyDir: {}